//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETMUON
    {
        public int SOPHIEUMUON { get; set; }
        public string MADUNGCU { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<System.TimeSpan> GIOTRA { get; set; }
    
        public virtual DUNGCU DUNGCU { get; set; }
        public virtual MUON MUON { get; set; }
    }
}
